import { z } from 'zod'

export const RawPatientSchema = z.object({ id: z.string(), name: z.string(), age: z.coerce.number(), gender: z.string(), symptoms: z.array(z.string()).default([]), heartRate: z.coerce.number().nullable().optional(), heart_rate: z.coerce.number().nullable().optional(), hr: z.coerce.number().nullable().optional(), systolicBP: z.coerce.number().nullable().optional(), systolic_bp: z.coerce.number().nullable().optional(), diastolicBP: z.coerce.number().nullable().optional(), diastolic_bp: z.coerce.number().nullable().optional(), oxygen: z.coerce.number().nullable().optional(), oxygen_saturation: z.coerce.number().nullable().optional(), spo2: z.coerce.number().nullable().optional(), temperature: z.coerce.number().nullable().optional(), temperature_c: z.coerce.number().nullable().optional() }).passthrough()
export type RawPatientRecord = z.infer<typeof RawPatientSchema>
export type Patient = { id:string; name:string; age:number; gender:string; heartRate:number|null; systolicBP:number|null; diastolicBP:number|null; oxygen:number|null; temperature:number|null; symptoms:string[]; originalRecord: Record<string, unknown> }
export const TriageSchema = z.object({ status:z.enum(['VALID','FLAGGED']), score:z.number().optional(), severity:z.enum(['LOW','MODERATE','HIGH','CRITICAL']).optional(), triggeredRules:z.array(z.string()).optional(), reason:z.string().optional() })
export const CaseSchema = z.object({ caseId:z.string(), patient:z.object({id:z.string(),name:z.string(),age:z.number(),gender:z.string()}), vitals:z.object({heartRate:z.number().nullable(),systolicBP:z.number().nullable(),diastolicBP:z.number().nullable(),oxygen:z.number().nullable(),temperature:z.number().nullable()}), triage:TriageSchema, placement:z.object({status:z.enum(['ALLOCATED','WAITLIST']),wardId:z.string(),wardName:z.string(),bedAssigned:z.boolean()}), source:z.object({system:z.literal('intake'),originalId:z.string()}), processedAt:z.string() })
export type TriageCase = z.infer<typeof CaseSchema>
export type Ward = { wardId:string; wardName:string; availableBeds:number; availableStaff:number; acuityLimit:number }
export function normalizeWard(record:Record<string,unknown>):Ward{const name=String(record.wardName??record.ward??'');return {wardId:String(record.wardId??name.toLowerCase()),wardName:name,availableBeds:Number(record.availableBeds??record.beds??0),availableStaff:Number(record.availableStaff??record.staff??0),acuityLimit:Number(record.acuityLimit??record.capacity??0)}}
export type Severity = 'LOW'|'MODERATE'|'HIGH'|'CRITICAL'
