import { describe, expect, it } from 'vitest'
import { IntakeService } from '@/src/services/intake'
import { normalizePatient } from '@/src/services/normalization'
import { scorePatient, validateVitals } from '@/src/services/triage'
import { BedAllocationSolver } from '@/src/services/allocation'
import { TriageIntegrationService } from '@/src/services/pipeline'
import intake from '@/data/intake.json'

describe('triage integration',()=>{it('queue count matches source',async()=>{const result=await new TriageIntegrationService().processQueue();expect(result.cases).toHaveLength(intake.length)});it('high severity outranks low',()=>{const low=normalizePatient({id:'l',name:'Low',age:30,gender:'x',heartRate:70,systolicBP:120,diastolicBP:80,oxygen:98,temperature:36.7,symptoms:[]});const high=normalizePatient({id:'h',name:'High',age:30,gender:'x',heartRate:150,systolicBP:80,diastolicBP:50,oxygen:88,temperature:40,symptoms:[]});expect(scorePatient(high).score).toBeGreaterThan(scorePatient(low).score)});it('missing vitals are flagged without score',()=>{const p=normalizePatient({id:'x',name:'Missing',age:30,gender:'x',heartRate:null,systolicBP:120,diastolicBP:80,oxygen:98,temperature:36,symptoms:[]});expect(validateVitals(p)).toEqual({status:'FLAGGED',reason:'Incomplete vitals'})});it('impossible vitals are flagged',()=>{const p=normalizePatient({...intake[0],heartRate:400});expect(validateVitals(p).status).toBe('FLAGGED')});it('allocation waitlists without capacity',()=>{const solver=new BedAllocationSolver([{wardId:'icu',wardName:'ICU',availableBeds:0,availableStaff:4,acuityLimit:4}]);expect(solver.allocate('CRITICAL').status).toBe('WAITLIST')});it('allocation consumes beds',()=>{const solver=new BedAllocationSolver([{wardId:'g',wardName:'GENERAL',availableBeds:1,availableStaff:1,acuityLimit:2}]);expect(solver.allocate('MODERATE').status).toBe('ALLOCATED');expect(solver.allocate('MODERATE').status).toBe('WAITLIST')});it('normalizes aliases',()=>{const p=normalizePatient({id:'a',name:'Alias',age:20,gender:'x',heart_rate:70,systolic_bp:120,diastolic_bp:80,spo2:98,temperature_c:36.5,symptoms:[]});expect(p.heartRate).toBe(70);expect(p.oxygen).toBe(98)})})
